language: python
python:
- "3.5"

env:
  global:
  - secure: "qp45OTKp0vZs25dKPPKbHUlKOaS6VsZQAjN69EoWkmx57FfaaTwTyn8ivMotenhVi0/rkCdDAU/cv6SMsQgnWk0VmQtHLhbJUTM3jnPPvGaRr8+gIuugYvJSzvfkv8EJmF1OmEdyxlL96Unj8SKsMTnSTMVzYozaQd7FwHGgmllOG3N2Pcf1nLl7yv4V1IoJJhc6JlFCn8V5Vsd/h3SmqF2uuXHSI/dhtDp4ZAAWU3Wzs5e5AoDmjYdadQG70tzVxnapTLFMbbQnubySWx6J4gKXmqF1HvB7tILQ2/GBFQAbVOxXvscb9S5g78tw/En8xYGVtAdcWrxmsPZ91wUu4ziyURgFHRzgKZvdXiSikpCp4sRH1OTJc74AvmScgy9RF22JRr6wZy6C4tkawV8fsBgyvq9A3NGg4g2diOZp9+UvSw0koQYIxrmAMn/B6z7JYC/NhEv33eTq/P/s7tzmXkd231LexBtG6eW8Hq3807msDbEgC9A8Fw7apdERYaACpXSDQpHMixukjUbWp9yo4Me8scVwzgDgXt0y2mVv6jlqOwETvTEzI2bcckHUnb3RLRlN72g9rW137vU00VE7J4hstbFdwkWkI81oHfDmYpTPBwN+LlDvUYSFrwDltS8mthN6eAYvXEKN6UIg/SuFg45yBT7/E1V2Fj4Br50v5yM=" # PYPI_PASSWORD
  - PYPI_USER=niccokunzmann2

install:
- pip install -r schemas/test/requirements.txt twine
- sudo apt-get install default-jre

script:
- python schemas/test/test_schemas.py
- generators/generate_python_client.sh

before_deploy:
- mkdir dist
- cp generators/python_client/dist/* dist

deploy:
- provider: script
  script: twine upload dist/*
  file_glob: true
  on:
    branch: master
  repo: schul-cloud/ressources-api-v1
  distributions: "sdist bdist_wheel"
