---
swagger: "2.0"
info:
  description: "This is the specification for the content of Schul-Cloud.\nYou can find more information in the repository <https://github.com/schul-cloud/ressources-api-v1>.\n"
  version: "1.0.0"
  title: "Schul-Cloud Content API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Schul-Cloud Development Team"
    url: "https://schul-cloud.github.io"
  license:
    name: "AGPL"
    url: "https://github.com/schul-cloud/ressources-api-v1/blob/master/LICENSE"
host: "virtserver.swaggerhub.com"
basePath: "/niccokunzmann/schul-cloud-content-api/1.0.0"
tags:
- name: "ressource"
  description: "learning ressources"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/schul-cloud/ressources-api-v1#objects"
schemes:
- "https"
- "http"
paths:
  /ressources/ids:
    get:
      tags:
      - "ressource"
      summary: "Get the ids of all ressources of the client"
      operationId: "getRessources"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Ressources are listed."
          schema:
            type: "array"
            items:
              type: "string"
        405:
          description: "Invalid input"
  /ressources:
    post:
      tags:
      - "ressource"
      summary: "Add new ressources to the database"
      operationId: "addRessources"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "list of ressources to add"
        required: true
        schema:
          $ref: "#/definitions/Ressource"
      responses:
        200:
          description: "The ressource has beed added"
          schema:
            $ref: "#/definitions/inline_response_200"
        401:
          description: "Not authorized to modify this UUID."
        405:
          description: "Invalid input"
    delete:
      tags:
      - "ressource"
      summary: "Delete all ressources"
      operationId: "deleteRessources"
      consumes:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "The ressources have been deleted"
  /ressources/{ressourceId}:
    get:
      tags:
      - "ressource"
      summary: "Get a ressource."
      operationId: "getRessource"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ressourceId"
        in: "path"
        description: "ID of ressource that needs to be fetched"
        required: true
        type: "string"
      responses:
        200:
          description: "Ressources are listed."
          schema:
            $ref: "#/definitions/Ressource"
        404:
          description: "No ressource with this id was found"
    delete:
      tags:
      - "ressource"
      summary: "Delete a resource"
      operationId: "deleteRessource"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ressourceId"
        in: "path"
        description: "ID of ressource that needs to be fetched"
        required: true
        type: "string"
      responses:
        200:
          description: "Ressources are listed."
          schema:
            $ref: "#/definitions/Ressource"
        404:
          description: "No ressource with this id"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Ressource:
    type: "object"
    required:
    - "contentCategory"
    - "languages"
    - "license"
    - "mimeType"
    - "providers"
    - "title"
    - "url"
    properties:
      title:
        type: "string"
        example: "Schul-Cloud"
        description: "The title of the document."
      url:
        $ref: "#/definitions/URL"
      license:
        type: "array"
        items:
          $ref: "#/definitions/License"
      mimeType:
        type: "string"
        example: "text/html"
        description: "<https://tools.ietf.org/html/rfc2046>"
      providers:
        type: "array"
        description: "The entity providing this information."
        items:
          $ref: "#/definitions/Provider"
      contentCategory:
        $ref: "#/definitions/ContentCategory"
      languages:
        type: "array"
        items:
          $ref: "#/definitions/Language"
      subjects:
        type: "array"
        items:
          $ref: "#/definitions/Subject"
      thumbnail:
        $ref: "#/definitions/URL"
      size:
        type: "integer"
        format: "int64"
      dimensions:
        $ref: "#/definitions/Dimensions"
      duration:
        type: "number"
      contextUrl:
        $ref: "#/definitions/URL"
  URL:
    type: "string"
    example: "http://schul-cloud.org"
  License:
    type: "string"
  Provider:
    type: "string"
  ContentCategory:
    example: "l"
    enum:
    - "a"
    - "l"
    - "rl"
    - "t"
  Language:
    type: "string"
    example: "de-de"
  Subject:
    type: "string"
  Dimensions:
    type: "string"
  inline_response_200:
    required:
    - "id"
    properties:
      id:
        type: "string"
    description: "The location and identifier of the posted object"
externalDocs:
  description: "Find out more about the API"
  url: "https://github.com/schul-cloud/ressources-api-v1"
