---
swagger: "2.0"
info:
  description: "This is the specification fo rthe content of Schul-Cloud.\nYou can\
    \ find more information in the [repository](https://github.com/schul-cloud/ressources-api-v1).\n"
  version: "1.0.0"
  title: "Schul-Cloud Content API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Schul-Cloud Development Team"
    url: "https://schul-cloud.github.io"
  license:
    name: "AGPL"
    url: "https://github.com/schul-cloud/ressources-api-v1/blob/master/LICENSE"
host: "virtserver.swaggerhub.com"
basePath: "/niccokunzmann/schul-cloud-content-api/1.0.0"
tags:
- name: "ressource"
  description: "learning ressources"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/schul-cloud/ressources-api-v1#objects"
schemes:
- "https"
- "http"
paths:
  /ressources/ids:
    get:
      tags:
      - "ressource"
      summary: "Get the ids of all ressources of the client"
      operationId: "getRessourceIds"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Ressources are listed."
          schema:
            type: "array"
            items:
              type: "string"
        405:
          description: "Invalid input"
      security:
      - basic: []
      - api_key: []
  /ressources:
    post:
      tags:
      - "ressource"
      summary: "Add new ressources to the database"
      operationId: "addRessource"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "list of ressources to add"
        required: true
        schema:
          $ref: "#/definitions/Ressource"
      responses:
        200:
          description: "The ressource has beed added"
          schema:
            $ref: "#/definitions/inline_response_200"
        405:
          description: "Invalid input"
      security:
      - basic: []
      - api_key: []
    delete:
      tags:
      - "ressource"
      summary: "Delete all ressources"
      operationId: "deleteRessources"
      consumes:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "The ressources have been deleted"
      security:
      - basic: []
      - api_key: []
  /ressources/{ressourceId}:
    get:
      tags:
      - "ressource"
      summary: "Get a ressource."
      operationId: "getRessource"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ressourceId"
        in: "path"
        description: "ID of ressource that needs to be fetched"
        required: true
        type: "string"
      responses:
        200:
          description: "Ressources are listed."
          schema:
            $ref: "#/definitions/Ressource"
        404:
          description: "No ressource with this id was found"
      security:
      - basic: []
      - api_key: []
    delete:
      tags:
      - "ressource"
      summary: "Delete a resource"
      operationId: "deleteRessource"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ressourceId"
        in: "path"
        description: "ID of ressource that needs to be fetched"
        required: true
        type: "string"
      responses:
        200:
          description: "Ressources are listed."
          schema:
            $ref: "#/definitions/Ressource"
        404:
          description: "No ressource with this id"
      security:
      - basic: []
      - api_key: []
securityDefinitions:
  api_key:
    description: "The server may have security keys for specially trusted applications."
    type: "apiKey"
    name: "api_key"
    in: "header"
  basic:
    description: "authenticate agains a pre-set authentication provider"
    type: "basic"
definitions:
  Ressource:
    type: "object"
    description: "#$ref: \"https://github.com/schul-cloud/ressources-api-v1/raw/master/schemas/ressource/ressource.json\""
  inline_response_200:
    required:
    - "id"
    properties:
      id:
        type: "string"
    description: "The location and identifier of the posted object"
externalDocs:
  description: "Find out more about the API"
  url: "https://github.com/schul-cloud/ressources-api-v1"
